require "user.packer"
require "user.options"
require "user.keymaps"
require "user.nvim-tree"
require "user.lualine"
-- require "user.bufferline"
-- require "user.telescope"
-- require "user.treesitter"
-- require "user.autopairs"
-- require "user.lsp"
-- require "user.surround"
-- require "user.neoscroll"

