require "user.options"
require "user.keymaps"
-- require "user.telescope"
require "user.treesitter"
-- require "user.autopairs"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
-- require "user.colorscheme"
require "user.packer"
-- require "user.lsp"
-- require "user.surround"
-- require "user.neoscroll"
