require("brian.keys")
require("brian.options")
require("brian.plugins")
require("brian.whichkey")
require("brian.telescope")
require("brian.hop")
require("brian.colorizer")
require("brian.treesitter")
require("brian.neoscroll")
require("brian.null-ls")
require("brian.wiki")
require("brian.snippets")
require("brian.projects")
require("brian.todo-comments")
-- require "brian.icons"
-- require "brian.spectre"
